# List of potental additional strings in magnet link
replace = [".avi", "1.4", "5.1", "DVDRip", "DVDSCR", "BRRip", "XviD", "1CDRip", "aXXo", "[", "]", "(", ")", "{", "}",
           "{{", "}}", "x264", "x265", "720p", "StyLishSaLH (StyLish Release)", "DvDScr", "MP3", "HC HDRip", "HC HDRIP",
           "HDRip", "WebRip", "ETRG", "YIFY", "StyLishSaLH", "StyLish Release", "TrippleAudio", "EngHindiIndonesian",
           "385MB", "CooL GuY", "a2zRG", "x264", "Hindi", "AAC", "PSK", "CyBorG", "AC3", "MP3", " R6", "HDRip", "H264",
           "ESub", "AQOS", "ALLiANCE", "UNRATED", "ExtraTorrentRG", "BrRip", "mkv", "mpg", "DiAMOND", "UsaBitcom",
           "AMIABLE", "BRRIP", "XVID", "AbSurdiTy", "DVDRiP", "TASTE", "BluRay", "HR", "COCAIN", "_", ".", "BestDivX",
           "MAXSPEED", "Eng", "500MB", "FXG", "Ac3", "Feel", "Subs", "S4A", "BDRip", "FTW", "Xvid", "Noir", "1337x",
           "ReVoTT", "GlowGaze", "mp4", "Unrated", "hdrip", "ARCHiViST", "TheWretched", "www", "torrentfive", "com",
           "1080p", "1080", "SecretMyth", "Kingdom", "Release", "RISES", "DvDrip", "ViP3R", "RISES", "BiDA", "READNFO",
           "HELLRAZ0R", "tots", "BeStDivX", "UsaBit", "FASM", "NeroZ", "576p", "LiMiTED", "Series", "ExtraTorrent",
           "DVDRIP", "~", "BRRiP", "699MB", "700MB", "greenbud", "B89", "480p", "AMX", "007", "DVDrip", "h264", "phrax",
           "ENG", "TODE", "LiNE", "XVid", "sC0rp", "PTpower", "OSCARS", "DXVA", "MXMG", "3LT0N", "TiTAN", "4PlayHD",
           "HQ", "HDRiP", "MoH", "MP4", "BadMeetsEvil", "XViD", "3Li", "PTpOWeR", "3D", "HSBS", "CC", "RiPS", "WEBRip",
           "R5", "PSiG", "'GokU61", "GB", "GokU61", "NL", "EE", "Rel", "NL", "PSEUDO", "DVDScr", "Rip", "NeRoZ",
           "EXTENDED", "xvid", "WarrLord", "SCREAM", "MERRY", "XMAS", "iMB", "7o9", "Exclusive", "171",
           "DiDee", "v2", "WEB", "DL", "EVO", "EtMovies", "HEVC", "RMTeam", "X264", "N1C", "-EtMov", "Hive-CM8",
           "Hive CM8", "anoXmous", "CataVentos", "-Manning", "-", "Hades", "1CD", "PRE", "Hon3yHD", "UNCENSORED", 
           "Movies", "Sample", "☻rDX☻", "5 1", "1 45", "CAM1XBET", "EtMo", "LineNoGrp"]

unwanted_titles = ["Jurassic World: Fallen Kingdom", "A Prayer Before Dawn", "Skyscraper", "The Kissing Booth",
                  "Avengers: Infinity War", "Rampage", "A Quiet Place", "Ready Player One", "I Kill Giants",
                  "Tomb Raider", "Red Sparrow", "Game Night", "Call Me by Your Name", "The Shape of Water",
                  "Blade Runner 2049", "Pirates of the Caribbean: Dead Men Tell No Tales", "Get Out",
                  "La La Land", "The Revenant", "Logan", "Lady Bird", "Deadpool 2", "American Animals", "Upgrade",
                  "The Disaster Artist"]
